YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "mygis.Admin",
        "mygis.Admin.AppManager",
        "mygis.Admin.AppManager.Apps",
        "mygis.Admin.AppManager.Maps",
        "mygis.Admin.AppManager.Styles",
        "mygis.Admin.AppManager.URLs",
        "mygis.Admin.LayerManager",
        "mygis.Admin.LogManager",
        "mygis.Admin.MapManager",
        "mygis.Admin.MapManager.Layers",
        "mygis.Admin.MapManager.Macros",
        "mygis.Admin.MapManager.Maps",
        "mygis.Admin.MapManager.Permissions",
        "mygis.Admin.MapManager.QuickSearches",
        "mygis.Admin.UI",
        "mygis.Admin.UserManager",
        "mygis.Admin.Utilities",
        "mygis.Drawing",
        "mygis.Drawing.Editing",
        "mygis.Drawing.Exporting",
        "mygis.Drawing.Importing",
        "mygis.Drawing.Styling",
        "mygis.Map",
        "mygis.OLOverrides",
        "mygis.OLOverrides.mygis_Control",
        "mygis.OLOverrides.mygis_Control.mygis_GetFeature",
        "mygis.Printing",
        "mygis.Query",
        "mygis.Storage",
        "mygis.UI",
        "mygis.UI.Help",
        "mygis.UI.Hooks",
        "mygis.UI.Macros",
        "mygis.UI.MediaManager",
        "mygis.User",
        "mygis.User.Hooks",
        "mygis.User.ProfileInfo",
        "mygis.User.UI",
        "mygis.Utilities",
        "mygis.Utilities.projections"
    ],
    "modules": [],
    "allModules": []
} };
});